### ISSUE TITLE
Unexpected and incomplete control flows

### ISSUE THREAD

**Issue by jgladwig** [SD2E/paml#35]
I am seeing control flows that are unexpected control flows coming out of the LUDOX protocol. The main issue at the moment seems to be that most of the control flows are simple self loops (the source and target are identical).

Here is an example from the current test file:
```
<https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/ControlFlow1> <http://bioprotocols.org/uml#source> <https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/CallBehaviorAction1> .
<https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/ControlFlow1> <http://bioprotocols.org/uml#target> <https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/CallBehaviorAction1> .
<https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/ControlFlow1> <http://sbols.org/v3#displayId> "ControlFlow1" .
<https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/ControlFlow1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://bioprotocols.org/uml#ControlFlow> .
<https://bbn.com/scratch/iGEM_LUDOX_OD_calibration_2018/ControlFlow1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sbols.org/v3#Identified> .
```
Link: https://github.com/SD2E/paml/blob/main/test/testfiles/igem_ludox_test.nt#L261

It also appears that the control flow does not incorporate any initial nodes or final nodes. So even if the self loops are resolved I suspect that there may still need to be an addition of initial and final nodes (to indict where the control starts and ends).

**Comment by jakebeal** [comment]
The self-loops have been resolved, and initial nodes are being added.
Final nodes are not strictly required, and are not currently being added.
