### ISSUE TITLE
Type hinting is not backward compatible

### ISSUE THREAD

**Issue by bbartley** [SD2E/paml#46]
PAML tests fail on my machine which is using Python 3.8 because of backward compatibility issues with the type hints.

PAML currently uses the (admittedly, prettier) type hint conventions which were introduced in Python 3.9 that allow use of native collection types in the type hint:
https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections

An example is here:
https://github.com/SD2E/paml/blob/main/uml/__init__.py#L388

To maintain backward compatibility of type hints, we would want to use:
```
from typing import List

def activity_initiating_nodes(self) -> List[ActivityNode]
```

Our Github Actions is configured to use Python 3.9 as well.  I believe we want to maintain backward compatibility to Python 3.6?

**Comment by jakebeal** [comment]
Yes, please feel free to downgrade if needed.

**Comment by bbartley** [comment]
Fixed in https://github.com/SD2E/paml/commit/92b0a1359a14fd36235c5d27431f5ea93172cda6

(Accidentally pushed fix directly to main rather than a branch)
